// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"e-commerce/backend/internal/config"
	"e-commerce/backend/internal/database"
	"e-commerce/backend/internal/handler"
	"e-commerce/backend/internal/repository"
	"e-commerce/backend/internal/services"
	"e-commerce/backend/internal/utils"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeAllHandler initializes all handler with config
func InitializeAllHandler(config2 *config.Config) *Handler {
	categoryRepository := repository.NewCategoryRepository()
	productRepository := repository.NewProductRepository()
	productService := services.NewProductService(categoryRepository, productRepository)
	productHandler := handler.NewProductHandler(productService)
	addressRepository := repository.NewAddressRepository()
	userRepository := repository.NewUserReposiory()
	addressService := services.NewAddressService(addressRepository, userRepository)
	addressHandler := handler.NewAddressHandler(addressService)
	jwtService := ProvideJWTService(config2)
	activityLogRepository := repository.NewActivityLogRepository()
	roleRepository := repository.NewRoleRepository()
	passwordResetTokenRepository := repository.NewPasswordResetTokenRepository()
	authService := services.NewAuthService(jwtService, userRepository, activityLogRepository, roleRepository, passwordResetTokenRepository)
	authHandler := handler.NewAuthHandler(authService)
	userService := services.NewUserService(userRepository, activityLogRepository, roleRepository)
	userHandler := handler.NewUserHandler(userService)
	db := ProvideDB()
	rbacRepository := repository.NewRBACRepository(db)
	rbacService := services.NewRBACService(rbacRepository)
	diHandler := NewHandler(productHandler, addressHandler, authHandler, userHandler, rbacService, userService, jwtService)
	return diHandler
}

// wire.go:

// ProvideDB provides database connection
func ProvideDB() *gorm.DB {
	return database.DB
}

// ProvideJWTService provides JWT service instance with config
func ProvideJWTService(config2 *config.Config) *utils.JWTService {
	return utils.NewJWTService(config2)
}

// Repository Providers
var repositorySet = wire.NewSet(
	ProvideDB, repository.NewCategoryRepository, repository.NewProductRepository, repository.NewAddressRepository, repository.NewOrderRepository, repository.NewPasswordResetTokenRepository, repository.NewPaymentMethodRepository, repository.NewPaymentRepository, repository.NewPermissionRepository, repository.NewRBACRepository, repository.NewShippingRepository, repository.NewTransactionRepository, repository.NewUserReposiory, repository.NewActivityLogRepository, repository.NewRoleRepository,
)

// Service Providers
var serviceSet = wire.NewSet(services.NewProductService, services.NewAddressService, services.NewAuthService, services.NewOrderService, services.NewPaymentMethodService, services.NewPaymentService, services.NewRBACService, services.NewRoleService, services.NewShippingService, services.NewTransactionService, services.NewUserService)

// Utils Providers
var utilsSet = wire.NewSet(
	ProvideJWTService,
)

// Handler Providers
var handlerSet = wire.NewSet(handler.NewProductHandler, handler.NewAddressHandler, handler.NewUserHandler, handler.NewAuthHandler)

// Handler struct contains all handler and services
type Handler struct {
	ProductHandler *handler.ProductHandler
	AddressHandler *handler.AddressHandler
	AuthHandler    *handler.AuthHandler
	UserHandler    *handler.UserHandler

	// Services untuk middleware
	RBACService services.RBACService
	UserService services.UserService
	JWTService  *utils.JWTService
}

// NewHandler creates new Handler instance
func NewHandler(
	productHandler *handler.ProductHandler,
	addressHandler *handler.AddressHandler,
	authHandler *handler.AuthHandler,
	userHandler *handler.UserHandler,
	rbacService services.RBACService,
	userService services.UserService,
	jwtService *utils.JWTService,
) *Handler {
	return &Handler{
		ProductHandler: productHandler,
		AddressHandler: addressHandler,
		AuthHandler:    authHandler,
		UserHandler:    userHandler,
		RBACService:    rbacService,
		UserService:    userService,
		JWTService:     jwtService,
	}
}
