// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"e-commerce/backend/internal/config"
	"e-commerce/backend/internal/database"
	"e-commerce/backend/internal/handler"
	"e-commerce/backend/internal/repository"
	"e-commerce/backend/internal/services"
	"e-commerce/backend/internal/utils"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeAllHandler initializes all handler with config
func InitializeAllHandler(config2 *config.Config) *Handler {
	categoryRepository := repository.NewCategoryRepository()
	categoryService := services.NewCategoryService(categoryRepository)
	categoryHandler := handler.NewCategoryHandler(categoryService)
	productRepository := repository.NewProductRepository()
	productService := services.NewProductService(categoryRepository, productRepository)
	productHandler := handler.NewProductHandler(productService)
	addressRepository := repository.NewAddressRepository()
	userRepository := repository.NewUserReposiory()
	addressService := services.NewAddressService(addressRepository, userRepository)
	addressHandler := handler.NewAddressHandler(addressService)
	jwtService := ProvideJWTService(config2)
	activityLogRepository := repository.NewActivityLogRepository()
	roleRepository := repository.NewRoleRepository()
	passwordResetTokenRepository := repository.NewPasswordResetTokenRepository()
	authService := services.NewAuthService(jwtService, userRepository, activityLogRepository, roleRepository, passwordResetTokenRepository)
	authHandler := handler.NewAuthHandler(authService)
	userService := services.NewUserService(userRepository, activityLogRepository, roleRepository)
	userHandler := handler.NewUserHandler(userService)
	permissionRepository := repository.NewPermissionRepository()
	roleService := services.NewRoleService(roleRepository, permissionRepository)
	roleHandler := handler.NewRoleHandler(roleService)
	orderRepository := repository.NewOrderRepository()
	orderService := services.NewOrderService(orderRepository)
	orderHandler := handler.NewOrderHandler(orderService)
	paymentRepository := repository.NewPaymentRepository()
	transactionRepository := repository.NewTransactionRepository()
	paymentService := services.NewPaymentService(paymentRepository, transactionRepository)
	paymentHandler := handler.NewPaymentHandler(paymentService)
	paymentMethodRepository := repository.NewPaymentMethodRepository()
	paymentMethodService := services.NewPaymentMethodService(paymentMethodRepository)
	paymentMethodHandler := handler.NewPaymentMethodHandler(paymentMethodService)
	shippingRepository := repository.NewShippingRepository()
	shippingService := services.NewShippingService(shippingRepository)
	shippingHandler := handler.NewShippingHandler(shippingService)
	transactionService := services.NewTransactionService(transactionRepository, shippingRepository, addressRepository, paymentMethodRepository, orderRepository, productRepository)
	transactionHandler := handler.NewTransactionHandler(transactionService)
	healthHandler := handler.NewHealthHandler()
	db := ProvideDB()
	dashboardRepository := repository.NewDashboardRepository(db)
	dashboardService := services.NewDashboardService(dashboardRepository)
	dashboardHandler := handler.NewDashboardHandler(dashboardService)
	rbacRepository := repository.NewRBACRepository(db)
	rbacService := services.NewRBACService(rbacRepository)
	diHandler := NewHandler(categoryHandler, productHandler, addressHandler, authHandler, userHandler, roleHandler, orderHandler, paymentHandler, paymentMethodHandler, shippingHandler, transactionHandler, healthHandler, dashboardHandler, rbacService, userService, jwtService)
	return diHandler
}

// wire.go:

// ProvideDB provides database connection
func ProvideDB() *gorm.DB {
	return database.DB
}

// ProvideJWTService provides JWT service instance with config
func ProvideJWTService(config2 *config.Config) *utils.JWTService {
	return utils.NewJWTService(config2)
}

// Repository Providers
var repositorySet = wire.NewSet(
	ProvideDB, repository.NewCategoryRepository, repository.NewProductRepository, repository.NewAddressRepository, repository.NewOrderRepository, repository.NewPasswordResetTokenRepository, repository.NewPaymentMethodRepository, repository.NewPaymentRepository, repository.NewPermissionRepository, repository.NewRBACRepository, repository.NewShippingRepository, repository.NewTransactionRepository, repository.NewUserReposiory, repository.NewActivityLogRepository, repository.NewRoleRepository, repository.NewDashboardRepository,
)

// Service Providers
var serviceSet = wire.NewSet(services.NewCategoryService, services.NewProductService, services.NewAddressService, services.NewAuthService, services.NewOrderService, services.NewPaymentMethodService, services.NewPaymentService, services.NewRBACService, services.NewRoleService, services.NewShippingService, services.NewTransactionService, services.NewUserService, services.NewDashboardService)

// Utils Providers
var utilsSet = wire.NewSet(
	ProvideJWTService,
)

// Handler Providers
var handlerSet = wire.NewSet(handler.NewCategoryHandler, handler.NewProductHandler, handler.NewAddressHandler, handler.NewUserHandler, handler.NewAuthHandler, handler.NewRoleHandler, handler.NewOrderHandler, handler.NewShippingHandler, handler.NewPaymentHandler, handler.NewPaymentMethodHandler, handler.NewTransactionHandler, handler.NewHealthHandler, handler.NewDashboardHandler)

// Handler struct contains all handler and services
type Handler struct {
	CategoryHandler      *handler.CategoryHandler
	ProductHandler       *handler.ProductHandler
	AddressHandler       *handler.AddressHandler
	AuthHandler          *handler.AuthHandler
	UserHandler          *handler.UserHandler
	RoleHandler          *handler.RoleHandler
	OrderHandler         *handler.OrderHandler
	PaymentHandler       *handler.PaymentHandler
	PaymentMethodHandler *handler.PaymentMethodHandler
	ShippingHandler      *handler.ShippingHandler
	TransactionHandler   *handler.TransactionHandler
	HealthHandler        *handler.HealthHandler
	DashboardHandler     *handler.DashboardHandler

	// Services untuk middleware
	RBACService services.RBACService
	UserService services.UserService
	JWTService  *utils.JWTService
}

// NewHandler creates new Handler instance
func NewHandler(
	categoryHandler *handler.CategoryHandler,
	productHandler *handler.ProductHandler,

	addressHandler *handler.AddressHandler,
	authHandler *handler.AuthHandler,
	userHandler *handler.UserHandler,
	roleHandler *handler.RoleHandler,
	orderHandler *handler.OrderHandler,
	paymentHandler *handler.PaymentHandler,
	paymentMethodHandler *handler.PaymentMethodHandler,
	shippingHandler *handler.ShippingHandler,
	transactionHandler *handler.TransactionHandler,
	healthHandler *handler.HealthHandler,
	dashboardHandler *handler.DashboardHandler,
	rbacService services.RBACService,
	userService services.UserService,
	jwtService *utils.JWTService,
) *Handler {
	return &Handler{
		CategoryHandler:      categoryHandler,
		ProductHandler:       productHandler,
		AddressHandler:       addressHandler,
		AuthHandler:          authHandler,
		UserHandler:          userHandler,
		RoleHandler:          roleHandler,
		OrderHandler:         orderHandler,
		PaymentHandler:       paymentHandler,
		PaymentMethodHandler: paymentMethodHandler,
		ShippingHandler:      shippingHandler,
		TransactionHandler:   transactionHandler,
		HealthHandler:        healthHandler,
		DashboardHandler:     dashboardHandler,
		RBACService:          rbacService,
		UserService:          userService,
		JWTService:           jwtService,
	}
}
