// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/payment_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/payment_repository.go -destination=internal/mocks/mock_payment_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "e-commerce/backend/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockPaymentRepository is a mock of PaymentRepository interface.
type MockPaymentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentRepositoryMockRecorder
	isgomock struct{}
}

// MockPaymentRepositoryMockRecorder is the mock recorder for MockPaymentRepository.
type MockPaymentRepositoryMockRecorder struct {
	mock *MockPaymentRepository
}

// NewMockPaymentRepository creates a new mock instance.
func NewMockPaymentRepository(ctrl *gomock.Controller) *MockPaymentRepository {
	mock := &MockPaymentRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentRepository) EXPECT() *MockPaymentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPaymentRepository) Create(param models.Payment, tx *gorm.DB) (models.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", param, tx)
	ret0, _ := ret[0].(models.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPaymentRepositoryMockRecorder) Create(param, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPaymentRepository)(nil).Create), param, tx)
}

// Delete mocks base method.
func (m *MockPaymentRepository) Delete(param models.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", param)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPaymentRepositoryMockRecorder) Delete(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPaymentRepository)(nil).Delete), param)
}

// FindAll mocks base method.
func (m *MockPaymentRepository) FindAll(param models.PaymentListRequest) ([]models.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", param)
	ret0, _ := ret[0].([]models.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockPaymentRepositoryMockRecorder) FindAll(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockPaymentRepository)(nil).FindAll), param)
}

// FindById mocks base method.
func (m *MockPaymentRepository) FindById(paramId uint) (models.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", paramId)
	ret0, _ := ret[0].(models.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockPaymentRepositoryMockRecorder) FindById(paramId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockPaymentRepository)(nil).FindById), paramId)
}

// Update mocks base method.
func (m *MockPaymentRepository) Update(param models.Payment, tx *gorm.DB) (models.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", param, tx)
	ret0, _ := ret[0].(models.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPaymentRepositoryMockRecorder) Update(param, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPaymentRepository)(nil).Update), param, tx)
}
