// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/shipping_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/shipping_repository.go -destination=internal/mocks/mock_shipping_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "e-commerce/backend/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockShippingRepository is a mock of ShippingRepository interface.
type MockShippingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShippingRepositoryMockRecorder
	isgomock struct{}
}

// MockShippingRepositoryMockRecorder is the mock recorder for MockShippingRepository.
type MockShippingRepositoryMockRecorder struct {
	mock *MockShippingRepository
}

// NewMockShippingRepository creates a new mock instance.
func NewMockShippingRepository(ctrl *gomock.Controller) *MockShippingRepository {
	mock := &MockShippingRepository{ctrl: ctrl}
	mock.recorder = &MockShippingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShippingRepository) EXPECT() *MockShippingRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockShippingRepository) Create(param models.Shipping, tx *gorm.DB) (models.Shipping, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", param, tx)
	ret0, _ := ret[0].(models.Shipping)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockShippingRepositoryMockRecorder) Create(param, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockShippingRepository)(nil).Create), param, tx)
}

// Delete mocks base method.
func (m *MockShippingRepository) Delete(param models.Shipping) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", param)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockShippingRepositoryMockRecorder) Delete(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockShippingRepository)(nil).Delete), param)
}

// FindAll mocks base method.
func (m *MockShippingRepository) FindAll(param models.ShippingListRequest) ([]models.Shipping, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", param)
	ret0, _ := ret[0].([]models.Shipping)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockShippingRepositoryMockRecorder) FindAll(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockShippingRepository)(nil).FindAll), param)
}

// FindById mocks base method.
func (m *MockShippingRepository) FindById(paramId uint) (*models.Shipping, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", paramId)
	ret0, _ := ret[0].(*models.Shipping)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockShippingRepositoryMockRecorder) FindById(paramId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockShippingRepository)(nil).FindById), paramId)
}

// Update mocks base method.
func (m *MockShippingRepository) Update(param models.Shipping, tx *gorm.DB) (models.Shipping, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", param, tx)
	ret0, _ := ret[0].(models.Shipping)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockShippingRepositoryMockRecorder) Update(param, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockShippingRepository)(nil).Update), param, tx)
}
