// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/payment_method_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/payment_method_repository.go -destination=internal/mocks/mock_payment_method_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "e-commerce/backend/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockPaymentMethodRepository is a mock of PaymentMethodRepository interface.
type MockPaymentMethodRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentMethodRepositoryMockRecorder
	isgomock struct{}
}

// MockPaymentMethodRepositoryMockRecorder is the mock recorder for MockPaymentMethodRepository.
type MockPaymentMethodRepositoryMockRecorder struct {
	mock *MockPaymentMethodRepository
}

// NewMockPaymentMethodRepository creates a new mock instance.
func NewMockPaymentMethodRepository(ctrl *gomock.Controller) *MockPaymentMethodRepository {
	mock := &MockPaymentMethodRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentMethodRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentMethodRepository) EXPECT() *MockPaymentMethodRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPaymentMethodRepository) Create(param models.PaymentMethod, tx *gorm.DB) (models.PaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", param, tx)
	ret0, _ := ret[0].(models.PaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPaymentMethodRepositoryMockRecorder) Create(param, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPaymentMethodRepository)(nil).Create), param, tx)
}

// Delete mocks base method.
func (m *MockPaymentMethodRepository) Delete(param models.PaymentMethod) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", param)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPaymentMethodRepositoryMockRecorder) Delete(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPaymentMethodRepository)(nil).Delete), param)
}

// FindAll mocks base method.
func (m *MockPaymentMethodRepository) FindAll(param models.PaymentMethodListRequest) ([]models.PaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", param)
	ret0, _ := ret[0].([]models.PaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockPaymentMethodRepositoryMockRecorder) FindAll(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockPaymentMethodRepository)(nil).FindAll), param)
}

// FindById mocks base method.
func (m *MockPaymentMethodRepository) FindById(paramId uint) (*models.PaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", paramId)
	ret0, _ := ret[0].(*models.PaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockPaymentMethodRepositoryMockRecorder) FindById(paramId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockPaymentMethodRepository)(nil).FindById), paramId)
}

// Update mocks base method.
func (m *MockPaymentMethodRepository) Update(param models.PaymentMethod, tx *gorm.DB) (models.PaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", param, tx)
	ret0, _ := ret[0].(models.PaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPaymentMethodRepositoryMockRecorder) Update(param, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPaymentMethodRepository)(nil).Update), param, tx)
}
