// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/transaction_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/transaction_service.go -destination=internal/mocks/mock_transaction_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "e-commerce/backend/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTransactionService is a mock of TransactionService interface.
type MockTransactionService struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionServiceMockRecorder
	isgomock struct{}
}

// MockTransactionServiceMockRecorder is the mock recorder for MockTransactionService.
type MockTransactionServiceMockRecorder struct {
	mock *MockTransactionService
}

// NewMockTransactionService creates a new mock instance.
func NewMockTransactionService(ctrl *gomock.Controller) *MockTransactionService {
	mock := &MockTransactionService{ctrl: ctrl}
	mock.recorder = &MockTransactionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionService) EXPECT() *MockTransactionServiceMockRecorder {
	return m.recorder
}

// CreateTransaction mocks base method.
func (m *MockTransactionService) CreateTransaction(ctx context.Context, param models.CreateTransaction) (*models.TransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", ctx, param)
	ret0, _ := ret[0].(*models.TransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockTransactionServiceMockRecorder) CreateTransaction(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockTransactionService)(nil).CreateTransaction), ctx, param)
}

// FindAllTransaction mocks base method.
func (m *MockTransactionService) FindAllTransaction(param models.TransactionListRequest) (*[]models.TransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllTransaction", param)
	ret0, _ := ret[0].(*[]models.TransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllTransaction indicates an expected call of FindAllTransaction.
func (mr *MockTransactionServiceMockRecorder) FindAllTransaction(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllTransaction", reflect.TypeOf((*MockTransactionService)(nil).FindAllTransaction), param)
}

// FindTransactionById mocks base method.
func (m *MockTransactionService) FindTransactionById(txid string) (*models.TransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTransactionById", txid)
	ret0, _ := ret[0].(*models.TransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTransactionById indicates an expected call of FindTransactionById.
func (mr *MockTransactionServiceMockRecorder) FindTransactionById(txid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTransactionById", reflect.TypeOf((*MockTransactionService)(nil).FindTransactionById), txid)
}

// UpdateTransaction mocks base method.
func (m *MockTransactionService) UpdateTransaction(param models.UpdateTransaction) (*models.TransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransaction", param)
	ret0, _ := ret[0].(*models.TransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTransaction indicates an expected call of UpdateTransaction.
func (mr *MockTransactionServiceMockRecorder) UpdateTransaction(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransaction", reflect.TypeOf((*MockTransactionService)(nil).UpdateTransaction), param)
}
