// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/order_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/order_service.go -destination=internal/mocks/mock_order_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "e-commerce/backend/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrderService is a mock of OrderService interface.
type MockOrderService struct {
	ctrl     *gomock.Controller
	recorder *MockOrderServiceMockRecorder
	isgomock struct{}
}

// MockOrderServiceMockRecorder is the mock recorder for MockOrderService.
type MockOrderServiceMockRecorder struct {
	mock *MockOrderService
}

// NewMockOrderService creates a new mock instance.
func NewMockOrderService(ctrl *gomock.Controller) *MockOrderService {
	mock := &MockOrderService{ctrl: ctrl}
	mock.recorder = &MockOrderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderService) EXPECT() *MockOrderServiceMockRecorder {
	return m.recorder
}

// CancelOrder mocks base method.
func (m *MockOrderService) CancelOrder(id string, userId int64) (*models.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelOrder", id, userId)
	ret0, _ := ret[0].(*models.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelOrder indicates an expected call of CancelOrder.
func (mr *MockOrderServiceMockRecorder) CancelOrder(id, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrder", reflect.TypeOf((*MockOrderService)(nil).CancelOrder), id, userId)
}

// DeleteOrder mocks base method.
func (m *MockOrderService) DeleteOrder(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrder", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrder indicates an expected call of DeleteOrder.
func (mr *MockOrderServiceMockRecorder) DeleteOrder(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrder", reflect.TypeOf((*MockOrderService)(nil).DeleteOrder), id)
}

// FindAllOrder mocks base method.
func (m *MockOrderService) FindAllOrder(param models.OrderListRequest) (*[]models.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllOrder", param)
	ret0, _ := ret[0].(*[]models.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllOrder indicates an expected call of FindAllOrder.
func (mr *MockOrderServiceMockRecorder) FindAllOrder(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllOrder", reflect.TypeOf((*MockOrderService)(nil).FindAllOrder), param)
}

// FindById mocks base method.
func (m *MockOrderService) FindById(id string, userId int64) (*models.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", id, userId)
	ret0, _ := ret[0].(*models.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockOrderServiceMockRecorder) FindById(id, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockOrderService)(nil).FindById), id, userId)
}

// UpdateOrder mocks base method.
func (m *MockOrderService) UpdateOrder(param models.UpdateOrder) (*models.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrder", param)
	ret0, _ := ret[0].(*models.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrder indicates an expected call of UpdateOrder.
func (mr *MockOrderServiceMockRecorder) UpdateOrder(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrder", reflect.TypeOf((*MockOrderService)(nil).UpdateOrder), param)
}
