// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/product_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/product_service.go -destination=internal/mocks/mock_product_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "e-commerce/backend/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockProductService is a mock of ProductService interface.
type MockProductService struct {
	ctrl     *gomock.Controller
	recorder *MockProductServiceMockRecorder
	isgomock struct{}
}

// MockProductServiceMockRecorder is the mock recorder for MockProductService.
type MockProductServiceMockRecorder struct {
	mock *MockProductService
}

// NewMockProductService creates a new mock instance.
func NewMockProductService(ctrl *gomock.Controller) *MockProductService {
	mock := &MockProductService{ctrl: ctrl}
	mock.recorder = &MockProductServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductService) EXPECT() *MockProductServiceMockRecorder {
	return m.recorder
}

// AddColorVarianProduct mocks base method.
func (m *MockProductService) AddColorVarianProduct(productId int64, param models.CreateColorVarianRequest) (*models.ProductDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddColorVarianProduct", productId, param)
	ret0, _ := ret[0].(*models.ProductDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddColorVarianProduct indicates an expected call of AddColorVarianProduct.
func (mr *MockProductServiceMockRecorder) AddColorVarianProduct(productId, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddColorVarianProduct", reflect.TypeOf((*MockProductService)(nil).AddColorVarianProduct), productId, param)
}

// CreateProduct mocks base method.
func (m *MockProductService) CreateProduct(param models.CreateProductParam) (*models.ProductDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", param)
	ret0, _ := ret[0].(*models.ProductDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockProductServiceMockRecorder) CreateProduct(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockProductService)(nil).CreateProduct), param)
}

// DeleteProduct mocks base method.
func (m *MockProductService) DeleteProduct(id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockProductServiceMockRecorder) DeleteProduct(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockProductService)(nil).DeleteProduct), id)
}

// FindAllProduct mocks base method.
func (m *MockProductService) FindAllProduct(param models.ProductListRequest) (*[]models.ProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllProduct", param)
	ret0, _ := ret[0].(*[]models.ProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllProduct indicates an expected call of FindAllProduct.
func (mr *MockProductServiceMockRecorder) FindAllProduct(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllProduct", reflect.TypeOf((*MockProductService)(nil).FindAllProduct), param)
}

// FindProductById mocks base method.
func (m *MockProductService) FindProductById(id int64) (*models.ProductDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindProductById", id)
	ret0, _ := ret[0].(*models.ProductDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindProductById indicates an expected call of FindProductById.
func (mr *MockProductServiceMockRecorder) FindProductById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindProductById", reflect.TypeOf((*MockProductService)(nil).FindProductById), id)
}

// UpdateProduct mocks base method.
func (m *MockProductService) UpdateProduct(param models.UpdateProductParam) (*models.ProductDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", param)
	ret0, _ := ret[0].(*models.ProductDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockProductServiceMockRecorder) UpdateProduct(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockProductService)(nil).UpdateProduct), param)
}

// UpdateSizeVariants mocks base method.
func (m *MockProductService) UpdateSizeVariants(colorVarianID int64, sizesParam []models.UpdateSizeVarianRequest, tx *gorm.DB) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSizeVariants", colorVarianID, sizesParam, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSizeVariants indicates an expected call of UpdateSizeVariants.
func (mr *MockProductServiceMockRecorder) UpdateSizeVariants(colorVarianID, sizesParam, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSizeVariants", reflect.TypeOf((*MockProductService)(nil).UpdateSizeVariants), colorVarianID, sizesParam, tx)
}
