// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/activity_log_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/activity_log_repository.go -destination=internal/mocks/mock_activity_log_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "e-commerce/backend/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockActivityLogRepository is a mock of ActivityLogRepository interface.
type MockActivityLogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockActivityLogRepositoryMockRecorder
	isgomock struct{}
}

// MockActivityLogRepositoryMockRecorder is the mock recorder for MockActivityLogRepository.
type MockActivityLogRepositoryMockRecorder struct {
	mock *MockActivityLogRepository
}

// NewMockActivityLogRepository creates a new mock instance.
func NewMockActivityLogRepository(ctrl *gomock.Controller) *MockActivityLogRepository {
	mock := &MockActivityLogRepository{ctrl: ctrl}
	mock.recorder = &MockActivityLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivityLogRepository) EXPECT() *MockActivityLogRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockActivityLogRepository) Create(param models.ActivityLog, tx *gorm.DB) (models.ActivityLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", param, tx)
	ret0, _ := ret[0].(models.ActivityLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockActivityLogRepositoryMockRecorder) Create(param, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockActivityLogRepository)(nil).Create), param, tx)
}

// FindAll mocks base method.
func (m *MockActivityLogRepository) FindAll(param *models.ActivityLogListRequest) (*models.ActivityLogListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", param)
	ret0, _ := ret[0].(*models.ActivityLogListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockActivityLogRepositoryMockRecorder) FindAll(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockActivityLogRepository)(nil).FindAll), param)
}
