// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/role_reposiotry.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/role_reposiotry.go -destination=internal/mocks/mock_role_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "e-commerce/backend/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRoleRepository is a mock of RoleRepository interface.
type MockRoleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoleRepositoryMockRecorder
	isgomock struct{}
}

// MockRoleRepositoryMockRecorder is the mock recorder for MockRoleRepository.
type MockRoleRepositoryMockRecorder struct {
	mock *MockRoleRepository
}

// NewMockRoleRepository creates a new mock instance.
func NewMockRoleRepository(ctrl *gomock.Controller) *MockRoleRepository {
	mock := &MockRoleRepository{ctrl: ctrl}
	mock.recorder = &MockRoleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleRepository) EXPECT() *MockRoleRepositoryMockRecorder {
	return m.recorder
}

// AddPermission mocks base method.
func (m *MockRoleRepository) AddPermission(id uint, permissions *[]models.Permission) (*models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPermission", id, permissions)
	ret0, _ := ret[0].(*models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPermission indicates an expected call of AddPermission.
func (mr *MockRoleRepositoryMockRecorder) AddPermission(id, permissions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPermission", reflect.TypeOf((*MockRoleRepository)(nil).AddPermission), id, permissions)
}

// Create mocks base method.
func (m *MockRoleRepository) Create(param models.Role) (models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", param)
	ret0, _ := ret[0].(models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRoleRepositoryMockRecorder) Create(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoleRepository)(nil).Create), param)
}

// Delete mocks base method.
func (m *MockRoleRepository) Delete(param models.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", param)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRoleRepositoryMockRecorder) Delete(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRoleRepository)(nil).Delete), param)
}

// FindAll mocks base method.
func (m *MockRoleRepository) FindAll() ([]models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockRoleRepositoryMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockRoleRepository)(nil).FindAll))
}

// FindById mocks base method.
func (m *MockRoleRepository) FindById(paramId uint) (models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", paramId)
	ret0, _ := ret[0].(models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockRoleRepositoryMockRecorder) FindById(paramId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockRoleRepository)(nil).FindById), paramId)
}

// FindByName mocks base method.
func (m *MockRoleRepository) FindByName(name string) (models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", name)
	ret0, _ := ret[0].(models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockRoleRepositoryMockRecorder) FindByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockRoleRepository)(nil).FindByName), name)
}

// FindByNameAndId mocks base method.
func (m *MockRoleRepository) FindByNameAndId(name string, id uint) (*models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNameAndId", name, id)
	ret0, _ := ret[0].(*models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNameAndId indicates an expected call of FindByNameAndId.
func (mr *MockRoleRepositoryMockRecorder) FindByNameAndId(name, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNameAndId", reflect.TypeOf((*MockRoleRepository)(nil).FindByNameAndId), name, id)
}

// Update mocks base method.
func (m *MockRoleRepository) Update(param models.Role) (models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", param)
	ret0, _ := ret[0].(models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRoleRepositoryMockRecorder) Update(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRoleRepository)(nil).Update), param)
}

// UpdatePermission mocks base method.
func (m *MockRoleRepository) UpdatePermission(id uint, permissions *[]models.Permission) (*models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePermission", id, permissions)
	ret0, _ := ret[0].(*models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePermission indicates an expected call of UpdatePermission.
func (mr *MockRoleRepositoryMockRecorder) UpdatePermission(id, permissions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePermission", reflect.TypeOf((*MockRoleRepository)(nil).UpdatePermission), id, permissions)
}
