// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/product_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/product_repository.go -destination=internal/mocks/mock_product_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "e-commerce/backend/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockProductRepository is a mock of ProductRepository interface.
type MockProductRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryMockRecorder
	isgomock struct{}
}

// MockProductRepositoryMockRecorder is the mock recorder for MockProductRepository.
type MockProductRepositoryMockRecorder struct {
	mock *MockProductRepository
}

// NewMockProductRepository creates a new mock instance.
func NewMockProductRepository(ctrl *gomock.Controller) *MockProductRepository {
	mock := &MockProductRepository{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepository) EXPECT() *MockProductRepositoryMockRecorder {
	return m.recorder
}

// CreateColorVarian mocks base method.
func (m *MockProductRepository) CreateColorVarian(param models.ColorVarian, tx *gorm.DB) (models.ColorVarian, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateColorVarian", param, tx)
	ret0, _ := ret[0].(models.ColorVarian)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateColorVarian indicates an expected call of CreateColorVarian.
func (mr *MockProductRepositoryMockRecorder) CreateColorVarian(param, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateColorVarian", reflect.TypeOf((*MockProductRepository)(nil).CreateColorVarian), param, tx)
}

// CreateProduct mocks base method.
func (m *MockProductRepository) CreateProduct(param models.Product, tx *gorm.DB) (models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", param, tx)
	ret0, _ := ret[0].(models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockProductRepositoryMockRecorder) CreateProduct(param, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockProductRepository)(nil).CreateProduct), param, tx)
}

// CreateSizeVarian mocks base method.
func (m *MockProductRepository) CreateSizeVarian(param models.SizeVarian, tx *gorm.DB) (models.SizeVarian, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSizeVarian", param, tx)
	ret0, _ := ret[0].(models.SizeVarian)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSizeVarian indicates an expected call of CreateSizeVarian.
func (mr *MockProductRepositoryMockRecorder) CreateSizeVarian(param, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSizeVarian", reflect.TypeOf((*MockProductRepository)(nil).CreateSizeVarian), param, tx)
}

// DeleteColorVarian mocks base method.
func (m *MockProductRepository) DeleteColorVarian(param int64, tx *gorm.DB) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteColorVarian", param, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteColorVarian indicates an expected call of DeleteColorVarian.
func (mr *MockProductRepositoryMockRecorder) DeleteColorVarian(param, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteColorVarian", reflect.TypeOf((*MockProductRepository)(nil).DeleteColorVarian), param, tx)
}

// DeleteProduct mocks base method.
func (m *MockProductRepository) DeleteProduct(paramid int64, tx *gorm.DB) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", paramid, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockProductRepositoryMockRecorder) DeleteProduct(paramid, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockProductRepository)(nil).DeleteProduct), paramid, tx)
}

// DeleteSizeVarian mocks base method.
func (m *MockProductRepository) DeleteSizeVarian(param int64, tx *gorm.DB) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSizeVarian", param, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSizeVarian indicates an expected call of DeleteSizeVarian.
func (mr *MockProductRepositoryMockRecorder) DeleteSizeVarian(param, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSizeVarian", reflect.TypeOf((*MockProductRepository)(nil).DeleteSizeVarian), param, tx)
}

// FindAllColorVarian mocks base method.
func (m *MockProductRepository) FindAllColorVarian(param models.ColorVarianListRequest, tx *gorm.DB) ([]models.ColorVarian, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllColorVarian", param, tx)
	ret0, _ := ret[0].([]models.ColorVarian)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllColorVarian indicates an expected call of FindAllColorVarian.
func (mr *MockProductRepositoryMockRecorder) FindAllColorVarian(param, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllColorVarian", reflect.TypeOf((*MockProductRepository)(nil).FindAllColorVarian), param, tx)
}

// FindAllProduct mocks base method.
func (m *MockProductRepository) FindAllProduct(param models.ProductListRequest, tx *gorm.DB) ([]models.Product, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllProduct", param, tx)
	ret0, _ := ret[0].([]models.Product)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAllProduct indicates an expected call of FindAllProduct.
func (mr *MockProductRepositoryMockRecorder) FindAllProduct(param, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllProduct", reflect.TypeOf((*MockProductRepository)(nil).FindAllProduct), param, tx)
}

// FindAllSizeVarian mocks base method.
func (m *MockProductRepository) FindAllSizeVarian(param models.SizeVarianListRequest, tx *gorm.DB) ([]models.SizeVarian, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllSizeVarian", param, tx)
	ret0, _ := ret[0].([]models.SizeVarian)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllSizeVarian indicates an expected call of FindAllSizeVarian.
func (mr *MockProductRepositoryMockRecorder) FindAllSizeVarian(param, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllSizeVarian", reflect.TypeOf((*MockProductRepository)(nil).FindAllSizeVarian), param, tx)
}

// FindByNameAndCategory mocks base method.
func (m *MockProductRepository) FindByNameAndCategory(name string, categoryID int64, tx *gorm.DB) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNameAndCategory", name, categoryID, tx)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNameAndCategory indicates an expected call of FindByNameAndCategory.
func (mr *MockProductRepositoryMockRecorder) FindByNameAndCategory(name, categoryID, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNameAndCategory", reflect.TypeOf((*MockProductRepository)(nil).FindByNameAndCategory), name, categoryID, tx)
}

// FindColorVarianById mocks base method.
func (m *MockProductRepository) FindColorVarianById(id int64, tx *gorm.DB) (models.ColorVarian, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindColorVarianById", id, tx)
	ret0, _ := ret[0].(models.ColorVarian)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindColorVarianById indicates an expected call of FindColorVarianById.
func (mr *MockProductRepositoryMockRecorder) FindColorVarianById(id, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindColorVarianById", reflect.TypeOf((*MockProductRepository)(nil).FindColorVarianById), id, tx)
}

// FindColorVarianByProductId mocks base method.
func (m *MockProductRepository) FindColorVarianByProductId(productId int64, tx *gorm.DB) ([]models.ColorVarian, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindColorVarianByProductId", productId, tx)
	ret0, _ := ret[0].([]models.ColorVarian)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindColorVarianByProductId indicates an expected call of FindColorVarianByProductId.
func (mr *MockProductRepositoryMockRecorder) FindColorVarianByProductId(productId, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindColorVarianByProductId", reflect.TypeOf((*MockProductRepository)(nil).FindColorVarianByProductId), productId, tx)
}

// FindProductById mocks base method.
func (m *MockProductRepository) FindProductById(id int64, tx *gorm.DB) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindProductById", id, tx)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindProductById indicates an expected call of FindProductById.
func (mr *MockProductRepositoryMockRecorder) FindProductById(id, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindProductById", reflect.TypeOf((*MockProductRepository)(nil).FindProductById), id, tx)
}

// FindSizeVarianByColorVarianId mocks base method.
func (m *MockProductRepository) FindSizeVarianByColorVarianId(colorVarianId int64, tx *gorm.DB) ([]models.SizeVarian, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSizeVarianByColorVarianId", colorVarianId, tx)
	ret0, _ := ret[0].([]models.SizeVarian)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSizeVarianByColorVarianId indicates an expected call of FindSizeVarianByColorVarianId.
func (mr *MockProductRepositoryMockRecorder) FindSizeVarianByColorVarianId(colorVarianId, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSizeVarianByColorVarianId", reflect.TypeOf((*MockProductRepository)(nil).FindSizeVarianByColorVarianId), colorVarianId, tx)
}

// FindSizeVarianById mocks base method.
func (m *MockProductRepository) FindSizeVarianById(id int64, tx *gorm.DB) (models.SizeVarian, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSizeVarianById", id, tx)
	ret0, _ := ret[0].(models.SizeVarian)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSizeVarianById indicates an expected call of FindSizeVarianById.
func (mr *MockProductRepositoryMockRecorder) FindSizeVarianById(id, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSizeVarianById", reflect.TypeOf((*MockProductRepository)(nil).FindSizeVarianById), id, tx)
}

// FindSizeVarianLocked mocks base method.
func (m *MockProductRepository) FindSizeVarianLocked(tx *gorm.DB, id uint) (*models.SizeVarian, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSizeVarianLocked", tx, id)
	ret0, _ := ret[0].(*models.SizeVarian)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSizeVarianLocked indicates an expected call of FindSizeVarianLocked.
func (mr *MockProductRepositoryMockRecorder) FindSizeVarianLocked(tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSizeVarianLocked", reflect.TypeOf((*MockProductRepository)(nil).FindSizeVarianLocked), tx, id)
}

// UpdateColorVarian mocks base method.
func (m *MockProductRepository) UpdateColorVarian(param models.ColorVarian, tx *gorm.DB) (models.ColorVarian, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateColorVarian", param, tx)
	ret0, _ := ret[0].(models.ColorVarian)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateColorVarian indicates an expected call of UpdateColorVarian.
func (mr *MockProductRepositoryMockRecorder) UpdateColorVarian(param, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateColorVarian", reflect.TypeOf((*MockProductRepository)(nil).UpdateColorVarian), param, tx)
}

// UpdateProduct mocks base method.
func (m *MockProductRepository) UpdateProduct(param models.Product, tx *gorm.DB) (models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", param, tx)
	ret0, _ := ret[0].(models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockProductRepositoryMockRecorder) UpdateProduct(param, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockProductRepository)(nil).UpdateProduct), param, tx)
}

// UpdateSizeVarian mocks base method.
func (m *MockProductRepository) UpdateSizeVarian(param models.SizeVarian, tx *gorm.DB) (models.SizeVarian, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSizeVarian", param, tx)
	ret0, _ := ret[0].(models.SizeVarian)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSizeVarian indicates an expected call of UpdateSizeVarian.
func (mr *MockProductRepositoryMockRecorder) UpdateSizeVarian(param, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSizeVarian", reflect.TypeOf((*MockProductRepository)(nil).UpdateSizeVarian), param, tx)
}
